-- El campo "punto" del evento logístico era texto libre: el operador podía escribir
-- cualquier cosa y "Centro Norte", "centro norte" y "Cento Norte" eran tres lugares
-- distintos para el sistema. Se introduce un catálogo de centros (centros de
-- distribución, puntos de recolección, oficinas) asociado al catálogo de ciudades,
-- con el mismo espíritu con que V4 resolvió el problema análogo para las ciudades.
--
-- La tabla se llama logistics_centers y no "centro": logistics ya tiene sus propias
-- tablas con el prefijo del módulo, en inglés y en plural (logistics_events,
-- logistics_tracked_shipments). cities es la única tabla que rompe ese patrón, y es
-- una excepción deliberada por ser dato compartido entre módulos; los centros no lo
-- son (solo los usa logistics), así que siguen la convención del módulo dueño.

create table logistics_centers (
    id bigint generated by default as identity,
    name varchar(160) not null,
    type varchar(30) not null,
    city_id bigint not null,
    address varchar(255) not null,
    active boolean not null default true,
    primary key (id),
    constraint fk_logistics_centers_city foreign key (city_id) references cities (id)
);

-- El autocompletado busca por nombre; el filtro por ciudad es tan frecuente como el
-- texto libre (un operador en bodega normalmente ya sabe en qué ciudad está).
create index idx_logistics_centers_name on logistics_centers (name);
create index idx_logistics_centers_city on logistics_centers (city_id);

-- Semilla: al menos dos centros por cada ciudad principal, con tipos distintos para
-- poder probar las reglas de coherencia sin depender de que alguien los cree a mano.
insert into logistics_centers (name, type, city_id, address, active) values
    ('Centro Norte', 'CENTRO_DISTRIBUCION',
        (select id from cities where name = 'MEDELLÍN' and department = 'ANTIOQUIA'),
        'Cra 65 #98-32, Medellín', true),
    ('Punto Poblado', 'PUNTO_RECOLECCION',
        (select id from cities where name = 'MEDELLÍN' and department = 'ANTIOQUIA'),
        'Cra 43A #6-15, El Poblado, Medellín', true),

    ('Centro Fontibón', 'CENTRO_DISTRIBUCION',
        (select id from cities where name = 'BOGOTÁ' and department = 'CUNDINAMARCA'),
        'Av. El Dorado #106-15, Bogotá', true),
    ('Oficina Chapinero', 'OFICINA',
        (select id from cities where name = 'BOGOTÁ' and department = 'CUNDINAMARCA'),
        'Cra 13 #55-10, Bogotá', true),

    ('Centro Yumbo-Cali', 'CENTRO_DISTRIBUCION',
        (select id from cities where name = 'CALI' and department = 'VALLE DEL CAUCA'),
        'Autopista Cali-Yumbo Km 3, Cali', true),
    ('Punto San Fernando', 'PUNTO_RECOLECCION',
        (select id from cities where name = 'CALI' and department = 'VALLE DEL CAUCA'),
        'Cra 30 #4-30, Cali', true),

    ('Centro Vía 40', 'CENTRO_DISTRIBUCION',
        (select id from cities where name = 'BARRANQUILLA' and department = 'ATLÁNTICO'),
        'Vía 40 #75-100, Barranquilla', true),
    ('Oficina Norte Barranquilla', 'OFICINA',
        (select id from cities where name = 'BARRANQUILLA' and department = 'ATLÁNTICO'),
        'Cra 51B #79-50, Barranquilla', true),

    ('Centro Mamonal', 'CENTRO_DISTRIBUCION',
        (select id from cities where name = 'CARTAGENA DE INDIAS' and department = 'BOLÍVAR'),
        'Zona Industrial Mamonal Km 5, Cartagena', true),
    ('Punto Bocagrande', 'PUNTO_RECOLECCION',
        (select id from cities where name = 'CARTAGENA DE INDIAS' and department = 'BOLÍVAR'),
        'Cra 1 #8-20, Bocagrande, Cartagena', true);
